In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("D:/jupyter-notebook/LiverCancer/Predict_Result/temp_result.csv")

rater_a = df.iloc[:,6].values.tolist()

rater_b = []
rater_b_temp = df.iloc[:,1:6].values.tolist()
for i in range(len(df)):
    max_index = rater_b_temp[i].index(max(rater_b_temp[i]))
    rater_b.append(max_index)

In [6]:
temp, conf = quadratic_weighted_kappa(rater_a,rater_b)

[[18798, 13, 22, 21, 19], [4, 18040, 8, 382, 28], [5, 2, 11791, 774, 225], [9, 53, 205, 30154, 1013], [2, 62, 57, 1040, 8837]]


In [81]:
temp_1, conf_1 = quadratic_weighted_kappa(rater_a,rater_b)

[[9, 0, 0, 0, 0], [0, 4, 0, 0, 0], [0, 0, 5, 0, 0], [0, 0, 0, 8, 0], [0, 0, 0, 0, 4]]


In [83]:
temp_2, conf_2 = quadratic_weighted_kappa(rater_a,rater_b)

[[9, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 6, 0, 0], [0, 0, 0, 4, 0], [0, 0, 0, 1, 5]]


In [59]:
temp_3, conf_3 = quadratic_weighted_kappa(rater_a,rater_b)

[[7, 0, 0, 0, 0], [0, 3, 0, 0, 0], [0, 0, 6, 1, 0], [0, 0, 1, 5, 0], [0, 0, 0, 0, 7]]


In [61]:
temp_4, conf_4 = quadratic_weighted_kappa(rater_a,rater_b)

[[7, 0, 0, 0, 0], [0, 4, 0, 0, 0], [1, 0, 4, 0, 0], [0, 2, 0, 3, 0], [0, 0, 0, 0, 9]]


In [63]:
temp_5, conf_5 = quadratic_weighted_kappa(rater_a,rater_b)

[[7, 0, 0, 0, 0], [0, 7, 0, 0, 0], [0, 0, 6, 1, 0], [0, 0, 0, 7, 0], [0, 0, 0, 0, 2]]


In [65]:
temp_6, conf_6 = quadratic_weighted_kappa(rater_a,rater_b)

[[10, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 5, 0, 0], [0, 0, 0, 6, 0], [0, 0, 1, 0, 3]]


In [67]:
temp_7, conf_7 = quadratic_weighted_kappa(rater_a,rater_b)

[[6, 0, 0, 0, 0], [0, 3, 0, 0, 0], [0, 0, 6, 0, 0], [0, 1, 1, 6, 1], [0, 0, 1, 0, 4]]


In [69]:
temp_8, conf_8 = quadratic_weighted_kappa(rater_a,rater_b)

[[7, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 5, 1, 0], [0, 0, 0, 5, 0], [0, 0, 0, 1, 5]]


In [71]:
temp_9, conf_9 = quadratic_weighted_kappa(rater_a,rater_b)

[[11, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 1, 4, 0], [0, 0, 1, 0, 4]]


In [73]:
temp_10, conf_10 = quadratic_weighted_kappa(rater_a,rater_b)

[[5, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 2, 0, 1], [0, 0, 0, 12, 0], [0, 0, 0, 0, 4]]


In [85]:
temp = np.array(conf_1) + np.array(conf_2) + np.array(conf_3) + np.array(conf_4) + np.array(conf_5)+ np.array(conf_6) + np.array(conf_7) + np.array(conf_8) + np.array(conf_9) + np.array(conf_10)
print(temp)

[[78  0  0  0  0]
 [ 0 46  0  0  0]
 [ 1  0 48  3  1]
 [ 0  3  3 60  1]
 [ 0  0  3  2 47]]


In [3]:
def quadratic_weighted_kappa(rater_a, rater_b, min_rating=None, max_rating=None): 
    
    rater_a = np.array(rater_a, dtype=int) 
    rater_b = np.array(rater_b, dtype=int) 
    
    assert(len(rater_a) == len(rater_b)) 
    
    if min_rating is None:
        min_rating = min(min(rater_a), min(rater_b))
    if max_rating is None:
        max_rating = max(max(rater_a), max(rater_b))
        
    conf_mat = confusion_matrix(rater_a, rater_b, min_rating, max_rating)
    
    print(conf_mat)
    
    num_ratings = len(conf_mat) 
    num_scored_items = float(len(rater_a)) 
    
    hist_rater_a = histogram(rater_a, min_rating, max_rating) 
    hist_rater_b = histogram(rater_b, min_rating, max_rating) 
    
    numerator = 0.0 
    denominator = 0.0 
    
    for i in range(num_ratings): 
        for j in range(num_ratings): 
            
            expected_count = (hist_rater_a[i] * hist_rater_b[j] / num_scored_items) 
            d = pow(i - j, 2.0) / pow(num_ratings - 1, 2.0) 
            numerator += d * conf_mat[i][j] / num_scored_items 
            denominator += d * expected_count / num_scored_items 
            
    return 1.0 - numerator / denominator, conf_mat 

# 一些封装起来的函数

In [4]:
def confusion_matrix(rater_a, rater_b, min_rating=None, max_rating=None):

    assert(len(rater_a) == len(rater_b))

    num_ratings = int(max_rating - min_rating + 1)

    conf_mat = [[0 for i in range(num_ratings)] for j in range(num_ratings)]

    for a, b in zip(rater_a, rater_b):

        conf_mat[a - min_rating][b - min_rating] += 1

    return conf_mat

In [5]:
def histogram(ratings, min_rating=None, max_rating=None):

    num_ratings = int(max_rating - min_rating + 1)

    hist_ratings = [0 for x in range(num_ratings)]

    for r in ratings:

        hist_ratings[r - min_rating] += 1
    
    return hist_ratings